config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  get 'welcome/main'
  get 'welcome/standardBooking'
  get 'welcome/deluxeBooking'
  get 'welcome/suiteBooking'
  get 'welcome/connectedBooking'
  get 'welcome/attractions'
  get 'welcome/aboutUs'
  get 'rooms/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#main'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
end
# app/controllers/data_controller.rb
class RoomsController < ApplicationController
    def index
        @data = rooms.all
        respond_to do |format|
            format.json { render json: @data }
        end
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to welcome_main_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :price, :from_date, :to_date, :firstName, :lastName, :userEmail)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moonlight Hotel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/edit.html.erb
<body class='background'>
    <h1 style='text-align:center;'>Your Room</h1>

    <%= render "form", room: @room %>
</body>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<body class="background">
  <div class="main">
    <div>
        <%= image_tag('logo.png', class:"mainIMG") %>
        <h1 class="Title">Moonlight Hotel</h1>
    </div>

    <nav class="navbar">
        <%= link_to 'Rooms', welcome_main_path, class:"navbar-item"%>
        <%= link_to 'Attrations', welcome_attractions_path, class:"navbar-item"%>
        <%= link_to 'About Us', welcome_aboutUs_path, class:"navbar-item"%>
    </nav>
  </div>

  <h1 id='roomType'></h1>
  <div class="slideshow-container">
    <div class='slides'></div>
      <a class="prev" onclick="changeSlide(-1)">&#10094;</a>
      <a class="next" onclick="changeSlide(1)">&#10095;</a>
    </div> 
    <div class="information">
      <table>
        <tr>
          <td><i class="range-square"></i></td>
          <td><p id='sq-ft'></p></td>
        </tr>
        <tr>
          <td> 
            <div class='svgFile'>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M32 32c17.7 0 32 14.3 32 32V320H288V160c0-17.7 14.3-32 32-32H544c53 0 96 43 96 96V448c0 17.7-14.3 32-32 32s-32-14.3-32-32V416H352 320 64v32c0 17.7-14.3 32-32 32s-32-14.3-32-32V64C0 46.3 14.3 32 32 32zm144 96a80 80 0 1 1 0 160 80 80 0 1 1 0-160z"/></svg>
            </div>
          </td>
          <td><p id='beds'></p></td>
        </tr>
        <tr>
          <td> 
            <div class='svgFile'>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M223.5 32C100 32 0 132.3 0 256S100 480 223.5 480c60.6 0 115.5-24.2 155.8-63.4c5-4.9 6.3-12.5 3.1-18.7s-10.1-9.7-17-8.5c-9.8 1.7-19.8 2.6-30.1 2.6c-96.9 0-175.5-78.8-175.5-176c0-65.8 36-123.1 89.3-153.3c6.1-3.5 9.2-10.5 7.7-17.3s-7.3-11.9-14.3-12.5c-6.3-.5-12.6-.8-19-.8z"/></svg>
            </div> 
          </td>
          <td><p id='sleeps'></p></td>
        </tr>
        <tr>
          <td> 
            <div class='svgFile'>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M54.2 202.9C123.2 136.7 216.8 96 320 96s196.8 40.7 265.8 106.9c12.8 12.2 33 11.8 45.2-.9s11.8-33-.9-45.2C549.7 79.5 440.4 32 320 32S90.3 79.5 9.8 156.7C-2.9 169-3.3 189.2 8.9 202s32.5 13.2 45.2 .9zM320 256c56.8 0 108.6 21.1 148.2 56c13.3 11.7 33.5 10.4 45.2-2.8s10.4-33.5-2.8-45.2C459.8 219.2 393 192 320 192s-139.8 27.2-190.5 72c-13.3 11.7-14.5 31.9-2.8 45.2s31.9 14.5 45.2 2.8c39.5-34.9 91.3-56 148.2-56zm64 160a64 64 0 1 0 -128 0 64 64 0 1 0 128 0z"/></svg>
            </div> 
          </td>
          <td><p>Free Internet Access</p></td>
        </tr>
        <tr>
          <td> 
            <div class='svgFile'>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zM192 256h48c17.7 0 32-14.3 32-32s-14.3-32-32-32H192v64zm48 64H192v32c0 17.7-14.3 32-32 32s-32-14.3-32-32V288 168c0-22.1 17.9-40 40-40h72c53 0 96 43 96 96s-43 96-96 96z"/></svg>
            </div> 
          </td>
          <td><p>Free Parking</p></td>
        </tr>
        <tr>
          <td> 
            <div class='svgFile'>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><!--! Font Awesome Pro 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M309.5 178.4L447.9 297.1c-1.6 .9-3.2 2-4.8 3c-18 12.4-40.1 20.3-59.2 20.3c-19.6 0-40.8-7.7-59.2-20.3c-22.1-15.5-51.6-15.5-73.7 0c-17.1 11.8-38 20.3-59.2 20.3c-10.1 0-21.1-2.2-31.9-6.2C163.1 193.2 262.2 96 384 96h64c17.7 0 32 14.3 32 32s-14.3 32-32 32H384c-26.9 0-52.3 6.6-74.5 18.4zM160 160A64 64 0 1 1 32 160a64 64 0 1 1 128 0zM306.5 325.9C329 341.4 356.5 352 384 352c26.9 0 55.4-10.8 77.4-26.1l0 0c11.9-8.5 28.1-7.8 39.2 1.7c14.4 11.9 32.5 21 50.6 25.2c17.2 4 27.9 21.2 23.9 38.4s-21.2 27.9-38.4 23.9c-24.5-5.7-44.9-16.5-58.2-25C449.5 405.7 417 416 384 416c-31.9 0-60.6-9.9-80.4-18.9c-5.8-2.7-11.1-5.3-15.6-7.7c-4.5 2.4-9.7 5.1-15.6 7.7c-19.8 9-48.5 18.9-80.4 18.9c-33 0-65.5-10.3-94.5-25.8c-13.4 8.4-33.7 19.3-58.2 25c-17.2 4-34.4-6.7-38.4-23.9s6.7-34.4 23.9-38.4c18.1-4.2 36.2-13.3 50.6-25.2c11.1-9.4 27.3-10.1 39.2-1.7l0 0C136.7 341.2 165.1 352 192 352c27.5 0 55-10.6 77.5-26.1c11.1-7.9 25.9-7.9 37 0z"/></svg>
            </div> 
          </td>
          <td><p>Pool</p></td>
        </tr>
      </table>
      <p id='base_price'></p>
      <p id='full_price'></p>
      <p id='link1'></p>
      <p id='link2'></p>
    </div>
  </div>
</body>
<br>

<%= render "form", room: @room %>
<script>
  //variables
  var currentSlide = 0;

  //Get Info of room
  function updatePulledInfo (){
    var params = ['roomType', 'bPrice', 'fPrice']
    var ids = ["roomType", "base_price", "full_price"];
    for (var i = 0; i < ids.length; i++) {
      var element = document.getElementById(ids[i]);
      var urlParams = new URLSearchParams(window.location.search);
      var getInfo = urlParams.get(params[i]);
      if (getInfo != element.textContent){
        element.textContent = getInfo;
        window.localStorage.setItem(ids[i], getInfo);
      }else if (localStorage.getItem(ids[i]) != null) {
        element.textContent = window.localStorage.getItem(ids[i]);
      }else{
        element.textContent = getInfo;
        window.localStorage.setItem(ids[i], getInfo);
      }
    }
  }

  //Post info into html
  function updateOtherInfo() {
    var idFields = ['roomTypeField', 'totalPriceField'];
    var idText = ['roomType', 'full_price'];
    var citedSourcesDiv = $('#cited-Sources');

    var field = document.getElementById('roomTypeField');
    var text = document.getElementById('roomType').textContent;
    field.value = text;

    var field = document.getElementById('totalPriceField');
    var text = document.getElementById('full_price').textContent;
    text = text.replace('/night', '');
    text = text.slice(-3);
    field.value = text;

    var roomFields = ['#sq-ft', '#beds', '#sleeps']
    var roomStandard = ['430 sq ft', '1 King Bed', 'Sleeps 2']
    var roomDeluxe = ['560 sq ft', '2 Queen Beds', 'Sleeps 4']
    var roomConnecting = ['650 sq ft', '4 Queen Beds', 'Sleeps 8']
    var roomSuite = ['780 sq ft', '1 King Beds', 'Sleeps 2']
    if (localStorage.getItem('roomType') == 'Standard Room') {
      for (var i = 0; i < 3; i++){
        p = document.querySelector(roomFields[i]);
        p.textContent = roomStandard[i];
      }
      citedSourcesDiv.append("<p><a href='https://www.flickr.com/photos/gothiatowers/15742160128/in/photostream/'>Standard Room</a>, by <a href='https://www.flickr.com/photos/gothiatowers/'>Gothia Towers</a> licensed under <a href='https://creativecommons.org/licenses/by/2.0'>CC BY 2.0</a></p>");
      citedSourcesDiv.append("<p><a href='https://www.flickr.com/photos/gothiatowers/15928945442/in/photostream/'>Standardrum Badrum 9-13</a>, by <a href='https://www.flickr.com/photos/gothiatowers/'>Gothia Towers</a> licensed under <a href='https://creativecommons.org/licenses/by/2.0'>CC BY 2.0</a></p>");
      
      var images = ['/assets/standard1.jpg','/assets/standard2.jpg'];
      createSlider(images);
    }else if (localStorage.getItem('roomType') == 'Deluxe Room') {
      for (var i = 0; i < 3; i++){
        p = document.querySelector(roomFields[i]);
        p.textContent = roomDeluxe[i];
      }
      citedSourcesDiv.append("<p><a href='https://commons.wikimedia.org/wiki/File:New_World_Petaling_Jaya_Hotel._2019-11-30_17-56-38.jpg#filelinks'>New World Petaling Jaya Hotel</a>, by <a href='https://commons.wikimedia.org/wiki/User:Shesmax'>Shesmax</a> licensed under <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a></p>");
      citedSourcesDiv.append("<p><a href='https://www.flickr.com/photos/hdv-gallery/6910235593'>Deluxe double room</a>, by <a href='https://www.flickr.com/photos/hdv-gallery/'>Hotel du Vin & Bistro</a> licensed under <a href='https://creativecommons.org/licenses/by/2.0'>CC BY 2.0</a></p>");
      
      var images = ['/assets/deluxe1.jpg','/assets/deluxe2.jpg'];
      createSlider(images);
    }else if (localStorage.getItem('roomType') == 'Connecting Room') {
      for (var i = 0; i < 3; i++){
        p = document.querySelector(roomFields[i]);
        p.textContent = roomConnecting[i];
      }
      citedSourcesDiv.append("<p><a href='https://creativecommons.org/licenses/by/2.0/, https://www.flickr.com/photos/portobaytrade/36893932826/in/photostream/'>hotel PORTOBAY RIO DE JANEIRO . Interconnecting Rooms</a>, by <a href='https://www.flickr.com/photos/portobaytrade/'>PortoBay Hotels & Resorts</a> licensed under <a href='https://creativecommons.org/licenses/by/2.0'>CC BY 2.0</a></p>");
      citedSourcesDiv.append("<p><a href='https://www.flickr.com/photos/portobaytrade/27252229556/in/photostream/'>Deluxe double room</a>, by <a href='https://www.flickr.com/photos/portobaytrade/'>PBM_JuniorSuite_Back_WC</a> licensed under <a href='https://creativecommons.org/licenses/by/2.0'>CC BY 2.0</a></p>");

      var images = ['/assets/connecting1.jpg','/assets/connecting2.jpg'];
      createSlider(images);
    }else if (localStorage.getItem('roomType') == 'Suite Room') {
      for (var i = 0; i < 3; i++){
        p = document.querySelector(roomFields[i]);
        p.textContent = roomSuite[i];
      }
      citedSourcesDiv.append("<p><a href='https://commons.wikimedia.org/wiki/File:Youma_Continental_Hotel.jpg'>Hotel</a>, by <a>youma continental hotel</a> licensed under <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a></p>");
      citedSourcesDiv.append("<p><a href='https://commons.wikimedia.org/wiki/File:Hotel_Suite_-_Living_Room_1.JPG'>Hotel Suite - Living Room</a>, by <a>Quant</a> licensed under <a href='https://creativecommons.org/licenses/by-sa/3.0/'>CC BY-SA 3.0</a></p>");
      
      var images = ['/assets/suite1.jpg','/assets/suite2.jpg'];
      createSlider(images);
    }
  }

  //Image Slider
  function createSlider(images){
    var carousel = document.querySelector('.slideshow-container');
    var slidesContainer = carousel.querySelector('.slides');
    var prevBtn = carousel.querySelector('.prev');
    var nextBtn = carousel.querySelector('.next');

    // Create slides dynamically
    images.forEach((imageSrc, index) => {
      var slide = document.createElement('div');
      slide.classList.add('mySlides');
      slide.classList.add('fade');
      if (index === currentSlide) {
        slide.classList.add('active');
        slide.style.display = 'block';
      }
      var img = document.createElement('img');
      img.src = imageSrc;
      slide.appendChild(img);
      slidesContainer.appendChild(slide);
    });
    currentSlide += 1;
  }

  // Add event listeners to buttons
  function changeSlide(n) {
    currentSlide = currentSlide + n;
    updateSlide();
  }

  // Update slide based on currentSlide
  function updateSlide() {
    var slides = document.getElementsByClassName("mySlides");
    if (currentSlide > slides.length) {
      currentSlide = 1;
    }
    if (currentSlide < 1) {
      currentSlide = slides.length;
    }
    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }
    for (let i = 0; i < slides.length; i++) {
      slides[i].className = slides[i].className.replace(" active", "");
    }
    slides[currentSlide - 1].style.display = "block";
    slides[currentSlide - 1].className += " active";
  }

  async function runInfo() {
    await updatePulledInfo();
    await updateOtherInfo();
  }
  runInfo();
</script>

app/views/rooms/show.html.erb
<body class="background">
  <div class="main">
    <div>
        <%= image_tag('logo.png', class:"mainIMG") %>
        <h1 class="Title">Moonlight Hotel</h1>
    </div>

    <nav class="navbar">
        <%= link_to 'Rooms', welcome_main_path, class:"navbar-item"%>
        <%= link_to 'Attrations', welcome_attractions_path, class:"navbar-item"%>
        <%= link_to 'About Us', welcome_aboutUs_path, class:"navbar-item"%>
    </nav>
  </div>

  <div class="confirmation-container">
    <h2>Confirmation Order Page</h2>
    <table>
      <tr>
          <th>First Name:</th>
          <td><%= @room.firstName %></td>
      </tr>
      <tr>
          <th>Last Name:</th>
          <td><%= @room.lastName %></td>
      </tr>
      <tr>
          <th>Email:</th>
          <td><%= @room.userEmail %></td>
      </tr>
      <tr>
          <th>Room Type:</th>
          <td><%= @room.name %></td>
      </tr>
      <tr>
          <th>Check-in Date:</th>
          <td><%= @room.from_date.strftime('%m-%d-%Y 4:00 PM') %></td>
      </tr>
      <tr>
          <th>Check-out Date:</th>
          <td><%= @room.to_date.strftime('%m-%d-%Y 11:00 AM') %></td>
      </tr>
      <tr>
          <th>Total Cost:</th>
          <td id='totalPrice'></td>
      </tr>
      <tr>
          <th>Additional Services:</th>
          <td>Breakfast, Room Service, Pool</td>
      </tr>
    </table>
    <p>Thank you for choosing our hotel. We look forward to seeing you soon!</p>
  </div>
  <div >
    <a href="#" onclick="window.print()" class='extraConfirm'>Print Confirmation Page</a>
    <br>
    <%= link_to "Change Check-In or Check-Out", edit_room_path(@room), class:'extraConfirm'%>
    <br>
    <%= link_to "Cancel this room", @room, class:'extraConfirm', method: :delete %>
  </div>
</body>

<script>

//Get database days
  var startDate;
  var endDate;

  $.ajax({
      url: '/rooms', 
      type: 'GET',
      dataType: 'json',
      success: function(data) {
        var latestRoom = data.length-1;
        // Loop through the data and add it to the 2D array
        let fromDate = new Date(data[latestRoom].from_date);
        let toDate = new Date(data[latestRoom].to_date);
        let fromDay = fromDate.getDate();
        let fromMonth = fromDate.getMonth()+1;
        let fromYear = fromDate.getFullYear();
        let toDay = toDate.getDate();
        let toMonth = toDate.getMonth()+1;
        let cost = data[latestRoom].price;

        // Create calendar after data is finished
        var totalDays = Math.ceil(Math.abs(toDate.getTime() - fromDate.getTime()) / (1000 * 3600 * 24));
        var totalPrice = cost*totalDays;
        var field = $('#totalPrice');
        field.text('$'+totalPrice);
      },
      error: function(jqXHR, textStatus, errorThrown) {
          console.log(textStatus + ': ' + errorThrown);
      }
  });
</script>

app/views/welcome/main.html.erb
<%# get to cmd prompt and get to users/pasha/documents/ this folder to launch the program the run live port on vs code%>
<body class="background">
    <div class="main">
        <div>
            <%= image_tag('logo.png', class:"mainIMG") %>
            <h1 class="Title">Moonlight Hotel</h1>
        </div>

        <nav class="navbar">
            <%= link_to 'Rooms', welcome_main_path, class:"navbar-item"%>
            <%= link_to 'Attrations', welcome_attractions_path, class:"navbar-item"%>
            <%= link_to 'About Us', welcome_aboutUs_path, class:"navbar-item"%>
        </nav>
    </div>
    <div class="price-range-feature">
        <label for="price-range">Filter by Price:</label>
        <input type="range" id="price-range" min="100" max="250" step="10" value="250">
        <span id="price-display">$100 - $250</span>
    </div>

    <div class="container">
        <div class="box" data-price="100">
            <div class="images-container">
                <%= image_tag('standard1.jpg', class:"images") %>
            </div>
            <div class="text">
                <h3>Standard Room</h3>
                <p class="base_price">$100</p>
                <p class="full_price">$110 includes taxes & fees</p>
                <%= link_to 'Reserve Room', rooms_new_path(roomType:'Standard Room', bPrice:'Price: $100/night', fPrice:'Full Price: $110/night'), class:"redirect-link"%>
            </div>
        </div>
        <div class="box" data-price="150">
            <div class="images-container">
                <%= image_tag('deluxe1.jpg', class:"images") %>
            </div>
            <div class="text">
                <h3>Deluxe Room</h3>
                <p class="base_price">$150</p>
                <p class="full_price">$170 includes taxes & fees</p>
                <%= link_to 'Reserve Room', rooms_new_path(roomType:'Deluxe Room', bPrice:'Price: $150/night', fPrice:'Full Price: $170/night'), class:"redirect-link"%>
            </div>
        </div>
        <div class="box" data-price="200">
            <div class="images-container">
                <%= image_tag('connecting1.jpg', class:"images") %>
            </div>
            <div class="text">
                <h3>Connecting Room</h3>
                <p class="base_price">$200</p>
                <p class="full_price">$220 includes taxes & fees</p>
                <%= link_to 'Reserve Room', rooms_new_path(roomType:'Connecting Room', bPrice:'Price: $200/night', fPrice:'Full Price: $220/night'), class:"redirect-link"%>
            </div>
        </div>
        <div class="box" data-price="200">
            <div class="images-container">
                <%= image_tag('suite1.jpg', class:"images") %>
            </div>
            <div class="text">
                <h3>Suite</h3>
                <p class="base_price">$230</p>
                <p class="full_price">$250 includes taxes & fees</p>
                <%= link_to 'Reserve Room', rooms_new_path(roomType:'Suite Room', bPrice:'Price: $230/night', fPrice:'Full Price: $250/night'), class:"redirect-link"%>
            </div>
        </div>
    </div>  

    <h1 class="titleLoc">Our Location</h1>  
    <div class="Location">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3314.7267749939356!2d-117.9229038839461!3d33.81936333741198!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80dcd62b3434c4b1%3A0x4ee319f1b1bc74d1!2sAnaheim%20Majestic%20Garden%20Hotel!5e0!3m2!1sen!2sus!4v1676434017996!5m2!1sen!2sus" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe> 
    </div>
    <div id='cited-Sources'>
        <p>
            <a href='https://www.flickr.com/photos/gothiatowers/15742160128/in/photostream/'>Standard Room</a>, by 
            <a href='https://www.flickr.com/photos/gothiatowers/'>Gothia Towers</a>
            licensed under 
            <a href='https://creativecommons.org/licenses/by/2.0'>CC BY 2.0</a>
        </p>
        <p>
            <a href='https://commons.wikimedia.org/wiki/File:New_World_Petaling_Jaya_Hotel._2019-11-30_17-56-38.jpg#filelinks'>New World Petaling Jaya Hotel</a>, by 
            <a href='https://commons.wikimedia.org/wiki/User:Shesmax'>Shesmax</a>
            licensed under 
            <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a>
        </p>
        <p>
            <a href='https://creativecommons.org/licenses/by/2.0/, https://www.flickr.com/photos/portobaytrade/36893932826/in/photostream/'>hotel PORTOBAY RIO DE JANEIRO . Interconnecting Rooms</a>, by 
            <a href='https://www.flickr.com/photos/portobaytrade/'>PortoBay Hotels & Resorts</a>
            licensed under 
            <a href='https://creativecommons.org/licenses/by/2.0'>CC BY 2.0</a>
        </p>
        <p>
            <a href='https://commons.wikimedia.org/wiki/File:Youma_Continental_Hotel.jpg'>Hotel</a>, by 
            <a>youma continental hotel</a>
            licensed under 
            <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a>
        </p>
    </div>

    
    <script>
        var priceRange = document.getElementById('price-range');
        var priceDisplay = document.getElementById('price-display');
        var roomBoxes = document.querySelectorAll('.box');

        // Update the price display when the price range changes
        priceRange.addEventListener('input', () => {
            var maxPrice = priceRange.value;
            var minPrice = priceRange.min;
            priceDisplay.textContent = `$${minPrice} - $${maxPrice}`;

            // Show or hide each room box based on its price
            roomBoxes.forEach(roomBox => {
                var roomPrice = parseInt(roomBox.dataset.price);
                if (roomPrice <= maxPrice) {
                    roomBox.style.display = 'flex';
                } else {
                    roomBox.style.display = 'none';
                }
            });
        });
    </script>
</body>